"""empty message

Revision ID: 582b6527f6c9
Revises: 
Create Date: 2022-08-03 11:56:48.183762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582b6527f6c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_name', sa.String(length=250), nullable=True),
    sa.Column('cafe_category', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=350), nullable=True),
    sa.Column('phone_number', sa.String(length=13), nullable=True),
    sa.Column('registration_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafe_cafe_name'), 'cafe', ['cafe_name'], unique=False)
    op.create_table('menu_of_dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_the_dish', sa.String(length=150), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('cafe_category', sa.String(length=150), nullable=True),
    sa.Column('cafe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafe'], ['cafe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_of_dishes_name_of_the_dish'), 'menu_of_dishes', ['name_of_the_dish'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_of_dishes_name_of_the_dish'), table_name='menu_of_dishes')
    op.drop_table('menu_of_dishes')
    op.drop_index(op.f('ix_cafe_cafe_name'), table_name='cafe')
    op.drop_table('cafe')
    # ### end Alembic commands ###
