"""empty message

Revision ID: f87b72938fa8
Revises: 
Create Date: 2022-08-03 14:08:11.608706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87b72938fa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_name', sa.String(length=250), nullable=True),
    sa.Column('cafe_category', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=350), nullable=True),
    sa.Column('phone_number', sa.String(length=13), nullable=True),
    sa.Column('registration_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_cafe_name'), 'institution', ['cafe_name'], unique=False)
    op.create_table('menu_of_dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_the_dish', sa.String(length=150), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('cafe_category', sa.String(length=150), nullable=True),
    sa.Column('cafe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafe'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_of_dishes_name_of_the_dish'), 'menu_of_dishes', ['name_of_the_dish'], unique=False)
    op.create_table('staff_institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('authority', sa.Integer(), nullable=True),
    sa.Column('cafe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafe'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_institution')
    op.drop_index(op.f('ix_menu_of_dishes_name_of_the_dish'), table_name='menu_of_dishes')
    op.drop_table('menu_of_dishes')
    op.drop_index(op.f('ix_institution_cafe_name'), table_name='institution')
    op.drop_table('institution')
    # ### end Alembic commands ###
